"""기능 영역의 공개 facade.

구현 모듈의 기능 함수를 안정적인 import 경로로 다시 노출한다.
"""

from .features.briefing_selections import (
    StoredBriefingTopicSelection,
    load_briefing_topic_selection,
    save_briefing_topic_selection,
)
from .features.users import db_001
from .features.personal_wiki import (
    UserSourceDocumentForAgent,
    PersistedWikiBuild,
    PersistedWikiDocument,
    RelationSupportSyncResult,
    RegisteredUrlSource,
    RelatedWikiKeyword,
    SavedUserSourceVersion,
    WikiChunkForEmbedding,
    WikiEmbeddingValue,
    WikiGraphRelationSnapshot,
    WikiNodeEmbedding,
    chunk_wiki_markdown,
    db_003,
    db_004,
    db_005,
    db_006,
    db_007,
    get_user_source_document_version_for_agent,
    get_wiki_chunks_for_embedding,
    list_existing_wiki_entries,
    list_existing_wiki_relations,
    list_onboarding_wiki_anchor_keys,
    list_related_wiki_keywords,
    list_wiki_graph_relation_snapshot,
    list_wiki_node_embeddings,
    list_user_source_versions_for_rebuild,
    mark_url_source_event,
    persist_wiki_build,
    persist_wiki_embeddings,
    register_user_url_source,
    retire_personal_wiki_without_sources,
    save_user_url_document_version,
    set_personal_wiki_scope,
    sync_wiki_relation_supports,
    supersede_personal_wiki_for_rebuild,
    update_full_wiki_rebuild_summary,
)
from .features.global_source import (
    CollectionTargetPlan,
    GlobalArticleToFetch,
    GlobalCollectionRunRecord,
    GlobalCollectionSchedule,
    claim_global_articles_for_fetch,
    db_008,
    db_009,
    db_010,
    db_011,
    db_012,
    db_013,
    db_014,
    load_collection_runs,
    load_collection_schedule,
    load_collection_schedules,
    mark_global_article_fetch_failed,
    persist_collected_articles,
    save_fetched_article_content,
    set_collection_schedule_status,
    update_collection_schedule,
    upsert_collection_schedule,
)
from .features.generation import db_015, db_016, db_017, db_018, db_019, db_020
from .features.recommendation import db_021
from .features.configuration import db_022, db_023, db_024, db_025
from .features.jobs import (
    ClaimAgentJobsCommand,
    ClaimedAgentJob,
    CompleteAgentJobCommand,
    CompletedAgentJobAnchor,
    EnqueuedCollectionRunJob,
    EnqueuedWikiBuildJob,
    FailAgentJobCommand,
    StoredAgentJob,
    claim_agent_job_by_id,
    create_completed_agent_job,
    claim_personal_wiki_jobs,
    claim_runnable_agent_jobs,
    complete_agent_job,
    complete_waiting_provider_job,
    db_026,
    defer_user_wiki_build_jobs,
    defer_agent_job_for_provider,
    enqueue_global_collection_run_job,
    enqueue_personal_wiki_build_job,
    enqueue_personal_wiki_maintenance_rebuild_job,
    enqueue_personal_wiki_rebuild_job,
    list_users_for_maintenance_rebuild,
    enqueue_url_collection_job,
    fail_agent_job,
    extend_agent_job_lease,
    get_agent_job,
    get_agent_jobs,
    list_runnable_agent_jobs,
    release_user_wiki_build_jobs,
    set_system_job_scope,
)
from .features.source_ingestion import (
    ContentMarkBindingNotFoundError,
    GeneratedContentNotFoundError,
    PersistedMcpSourceSubmission,
    PersistedSourceSubmission,
    db_002,
    deactivate_content_mark_and_enqueue_rebuild,
    enqueue_wiki_rebuild_for_source,
    register_url_and_enqueue,
    save_content_mark_and_enqueue,
    save_fetched_url_and_enqueue,
    save_mcp_source_submission,
    save_onboarding_seed_and_enqueue,
    save_web_clipping_and_enqueue,
)
from .features.generation_runtime import (
    PersistedGenerationSubmission,
    StaleContextVersionError,
    StoredUserContext,
    UserContextRequiredError,
    enqueue_report_generation_job,
    load_global_document_freshness,
    load_global_report_context,
    load_personal_wiki_vector_context,
    load_pinned_wiki_context,
    load_report_context,
    persist_report_generation,
    persist_report_navigation_snapshot,
    upsert_user_context_snapshot,
)
from .features.wiki_navigation import (
    load_wiki_navigation_keyword_candidates,
    load_wiki_navigation_pages,
    load_wiki_navigation_relations,
    load_wiki_navigation_sources,
    load_wiki_navigation_vector_candidates,
)
from .features.change_history_facts import (
    list_change_history_facts,
    load_change_history_facts_by_ids,
    load_latest_change_history_run,
    load_latest_report_snapshot,
    persist_change_history_run,
    search_change_history_facts,
)
from .features.interest_taxonomy import (
    InterestTaxonomyConflictError,
    StoredInterestTaxonomy,
    sync_user_interest_subscriptions,
    sync_wiki_interest_collection_targets,
    upsert_interest_taxonomy_snapshot,
)
from .features.onboarding_contexts import (
    list_cached_custom_topic_contexts,
    list_onboarding_topic_contexts,
    save_custom_topic_contexts,
)
from .features.events import db_027
from .features.api_keys import db_028
from .features.usage import db_029
from .features.provider_rate_limits import (
    ProviderRateLimitDecision,
    observe_provider_rate_limits,
    parse_rate_limit_reset,
    reserve_provider_capacity,
)
from .features.llm_batches import (
    ClaimedBatchResultItem,
    DueLlmBatch,
    EnqueueLlmBatchItemCommand,
    PreparedLlmBatch,
    PreparedLlmBatchItem,
    ProviderBatchSnapshot,
    StoredLlmBatchItem,
    apply_llm_batch_result_lines,
    claim_due_llm_batches,
    claim_llm_batch,
    claim_unapplied_batch_results,
    enqueue_llm_batch_item,
    mark_batch_result_applied,
    mark_llm_batch_submitted,
    release_batch_result_application,
    release_failed_llm_batch_submission,
    update_llm_batch_snapshot,
)
from .features.audit import db_030
from .features.interest_profiles import (
    ConnectionInterestProfileRepository,
    list_users_for_interest_recalculation,
    load_interest_documents_for_user,
    load_recent_feedback_signals_for_user,
    save_feedback_signals_for_user,
    save_interest_profile_for_user,
)
from .features.interest_bundles import ConnectionInterestBundleRepository
from .features.wiki_deletion import (
    WikiDocumentNotFoundError,
    delete_wiki_document_and_record_event,
)
from .features.wiki_reset import reset_personal_wiki
from .features.briefing_preparations import (
    StoredBriefingTopicSnapshot,
    enqueue_briefing_preparation_job,
    load_briefing_topic_snapshot,
    upsert_briefing_topic_snapshot,
)

__all__ = [
    "db_001",
    "db_002",
    "db_003",
    "db_004",
    "db_005",
    "db_006",
    "db_007",
    "db_008",
    "db_009",
    "db_010",
    "db_011",
    "db_012",
    "db_013",
    "db_014",
    "db_015",
    "db_016",
    "db_017",
    "db_018",
    "db_019",
    "db_020",
    "db_021",
    "db_022",
    "db_023",
    "db_024",
    "db_025",
    "db_026",
    "db_027",
    "db_028",
    "db_029",
    "db_030",
    "ProviderRateLimitDecision",
    "observe_provider_rate_limits",
    "parse_rate_limit_reset",
    "reserve_provider_capacity",
    "complete_waiting_provider_job",
    "defer_agent_job_for_provider",
    "ClaimedBatchResultItem",
    "DueLlmBatch",
    "EnqueueLlmBatchItemCommand",
    "PreparedLlmBatch",
    "PreparedLlmBatchItem",
    "ProviderBatchSnapshot",
    "StoredLlmBatchItem",
    "apply_llm_batch_result_lines",
    "claim_due_llm_batches",
    "claim_llm_batch",
    "claim_unapplied_batch_results",
    "enqueue_llm_batch_item",
    "mark_batch_result_applied",
    "mark_llm_batch_submitted",
    "release_batch_result_application",
    "release_failed_llm_batch_submission",
    "update_llm_batch_snapshot",
    "ConnectionInterestBundleRepository",
    "load_personal_wiki_vector_context",
    "RelationSupportSyncResult",
    "WikiGraphRelationSnapshot",
    "WikiNodeEmbedding",
    "list_onboarding_wiki_anchor_keys",
    "list_wiki_graph_relation_snapshot",
    "list_wiki_node_embeddings",
    "list_user_source_versions_for_rebuild",
    "list_onboarding_topic_contexts",
    "list_cached_custom_topic_contexts",
    "save_custom_topic_contexts",
    "supersede_personal_wiki_for_rebuild",
    "update_full_wiki_rebuild_summary",
    "save_fetched_url_and_enqueue",
    "sync_wiki_relation_supports",
    "reset_personal_wiki",
    "get_agent_jobs",
    "extend_agent_job_lease",
    "StoredBriefingTopicSelection",
    "load_briefing_topic_selection",
    "save_briefing_topic_selection",
    "StoredBriefingTopicSnapshot",
    "enqueue_briefing_preparation_job",
    "load_briefing_topic_snapshot",
    "upsert_briefing_topic_snapshot",
]
